name: Discord Nitro Generator
on: [push]
jobs:
  Generate_Nitro:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          architecture: 'x64'
      - run: python nitro_generator.py
